name: gql_http_link
version: 0.3.3
description: GQL Terminating Link to execute requests via HTTP using JSON.
repository: https://github.com/gql-dart/gql
environment:
  sdk: '>=2.7.2 <3.0.0'
dependencies:
  meta: ^1.3.0
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
  gql_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_link
  http: ^0.13.1
  http_parser: ^4.0.0
dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.3
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
  http_parser: ^4.0.0
