name: gql_error_link
version: 0.1.0
description: GQL Link to handle execution errors and exceptions
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  async: ^2.5.0
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
  gql_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_link
  meta: ^1.3.0
dev_dependencies: 
  test: ^1.16.5
  mockito: ^4.1.4
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
