name: gql_websocket_link
version: 0.2.0
description: GQL Websocket Link
repository: https://github.com/gql-dart/gql
environment:
  sdk: '>=2.7.2 <3.0.0'
dependencies:
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
  gql_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_link
  meta: ^1.3.0
  rxdart: ^0.26.0
  uuid_enhanced: ^3.0.2
  web_socket_channel: ^2.0.0
dev_dependencies:
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
  mockito: ^5.0.3
  test: ^1.16.8
