name: gql_websocket_link
version: 0.2.0
description: GQL Websocket Link
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  meta: ^1.1.8
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
  gql_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_link
  uuid_enhanced: ^3.0.2
  rxdart: ^0.25.0
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  web_socket_channel: ^1.1.0
dev_dependencies: 
  test: ^1.14.3
  mockito: ^4.1.1
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
