name: gql_transform_link
version: 0.1.5
description: GQL Link to transform Requests and Responses. May be used to update context, document, variables, data, errors, etc.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
  gql_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_link
dev_dependencies: 
  test: ^1.0.0
  mockito: ^4.1.1
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
