name: gql_link
version: 0.3.1
description: A simple and modular AST-based GraphQL request execution interface.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  meta: ^1.3.0
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
dev_dependencies: 
  test: ^1.16.5
  mockito: ^4.1.4
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
