name: gql
version: 0.12.4
description: GraphQL tools for parsing, transforming and printing GraphQL documents.
repository: https://github.com/gql-dart/gql
environment:
  sdk: '>=2.7.2 <3.0.0'
dependencies:
  collection: ^1.15.0
  meta: ^1.3.0
  source_span: ^1.8.1
dev_dependencies:
  cats:
    path: ../cats
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
  test: ^1.16.8
