name: gql_dio_link
version: 0.0.4
description: Similar to gql_http_link, gql_dio_link is a GQL Terminating Link to execute requests via Dio using JSON
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  dio: ^4.0.0
  gql_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_link
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
  meta: ^1.3.0
dev_dependencies: 
  test: ^1.16.5
  mockito: ^4.1.4
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
  collection: ^1.15.0
