name: gql_dedupe_link
version: 1.0.10
description: GQL Link to deduplicate identical in-flight execution requests
repository: https://github.com/gql-dart/gql
environment:
  sdk: '>=2.7.2 <3.0.0'
dependencies:
  meta: ^1.3.0
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
  gql_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_link
  async: ^2.5.0
dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.3
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
