name: gql_example_cli_github
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  args: any
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  gql_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_link
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
  gql_transform_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_transform_link
  gql_http_link:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_http_link
dev_dependencies: 
  build_runner: ^1.10.1
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
  gql_build:
    git:
      url: git://github.com/julienzarka/gql.git
      path: codegen/gql_build
