name: gql_code_builder
version: 0.1.4+1
description: Dart code builders taking *.graphql documents and SDL to build useful classes.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  analyzer: ^1.5.0
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  code_builder: ^4.0.0
  meta: ^1.3.0
  built_collection: ^5.0.0
  built_value: ^8.0.5
  path: ^1.8.0
  recase: ^4.0.0
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
dev_dependencies: 
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
  build_runner: ^2.0.1
  test: ^1.0.0
