name: gql_code_builder
version: 0.1.4+1
description: Dart code builders taking *.graphql documents and SDL to build useful classes.
repository: https://github.com/gql-dart/gql
environment:
  sdk: '>=2.7.2 <3.0.0'
dependencies:
  analyzer: ^1.3.0
  gql:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql
  code_builder: ^3.7.0
  meta: ^1.3.0
  built_collection: ^5.0.0
  built_value: ^8.0.4
  path: ^1.8.0
  recase: ^3.0.1
  gql_exec:
    git:
      url: git://github.com/julienzarka/gql.git
      path: links/gql_exec
dev_dependencies:
  gql_pedantic:
    git:
      url: git://github.com/julienzarka/gql.git
      path: gql_pedantic
  build_runner: ^1.12.2
  test: ^1.16.8
